### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by BTrosh** [UTrosh/LycTools#1]
Je suggère le jeux god of war 4

**Comment by BTrosh** [comment]
![Uploading Screenshot_2022-11-12-17-06-29-31_680d03679600f7af0b4c700c6b270fe7.jpg…]()

**Comment by UTrosh** [comment]
Pas les requirements

**Comment by OTrosh** [comment]
alors faut des jeux gratuit et comme tu comprends pas je vais te le redire les pc du lycée les tiennent pas
