### ISSUE TITLE
Erreur avec la liste de jeux et d'application 

### ISSUE THREAD

**Issue by Aa6ash** [UTrosh/LycTools#11]
Salut ! 

quand je tape app list pour voir la liste d'applications j'obtiens une suite de caractères incompréhensible et je ne peux donc rien installer.. il y a une solution ?

Ah et au fait l'invit du serv discord a expiré 

Merci d'avance pour votre aide

**Comment by UTrosh** [comment]
Hey, j'aurais besoin d'un screen s'il te plait, et si tu es sur la connexion de ton lycée, tu a essayé de répéter plusieurs fois la commande?

**Comment by UTrosh** [comment]
https://discord.gg/vsBc3BKHpg pour le discord

**Comment by Aa6ash** [comment]
![Capture d’écran (19)](https://user-images.githubusercontent.com/119050872/204005933-d0e0b454-d097-4c03-b71b-5b240061aac1.png)

Voici ce que j'obtiens quand je tape la commande
Et j'ai essayé sans être connecté au wifi du lycée mais ça ne change rien.

**Comment by Aa6ash** [comment]
C'est un hp probook 440 g9, j'ai la dernière version (v6)
Je n'ai pas eu de problème à l'installation ni au démarrage, c'est vraiment que quand j'essaye d'afficher la liste des apps et des jeux

**Comment by UTrosh** [comment]
très étrange, moyen de passer discord?

**Comment by Aa6ash** [comment]
Ok, je vais rejoindre le serv

**Comment by UTrosh** [comment]
Du au nouveau gui, le game list & app list ne fonctionne plus sur la V7
