### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by rotySmok** [UTrosh/LycTools#4]
kotor 
le lien https://www.swtor.com/fr
pour moi et mon modo naxxor

**Comment by UTrosh** [comment]
il me faut le lien direct vers le téléchargement

**Comment by rotySmok** [comment]
sais sur la page que je t ai envoyer sais en bas

**Comment by UTrosh** [comment]
il me faut le lien direct.

**Comment by rotySmok** [comment]
comment on fait

**Comment by rotySmok** [comment]
https://swotor-a.akamaihd.net/installer/SWTOR_setup.exe

**Comment by rotySmok** [comment]
https://swtor-a.akamaihd.net/installer/SWTOR_setup.exe

**Comment by UTrosh** [comment]
ajouté
